"""Create a standalone Kaggle script with the shared modules and optional config."""
import argparse
import base64
import io
from pathlib import Path
import zipfile


def bundle(entry, output, config=None):
    root = Path(__file__).parent
    allowed = {'train_audited.py','prepare_audited.py','summarize_audited.py',
               'build_x30.py','build_x31.py','launch_xla_audited.py',
               'compare_audited.py','rescore_legacy_oof.py'}
    if entry not in allowed:
        raise ValueError('Unsupported entrypoint')
    stream = io.BytesIO()
    with zipfile.ZipFile(stream,'w',zipfile.ZIP_DEFLATED) as z:
        for path in sorted((root/'audit').glob('*.py')):
            z.write(path,'audit/'+path.name)
        for name in allowed:
            z.write(root/name,name)
        if config:
            z.write(config,'config.json')
    payload = base64.b64encode(stream.getvalue()).decode('ascii')
    source = ('# Generated by bundle_audited.py.\n'
              'import base64, io, pathlib, runpy, sys, tempfile, zipfile\n'
              "if __name__ == '__main__':\n"
              '    with tempfile.TemporaryDirectory(prefix="mscapital-audit-") as d:\n'
              f'        zipfile.ZipFile(io.BytesIO(base64.b64decode({payload!r}))).extractall(d)\n'
              '        sys.path.insert(0,d)\n'
              + ('        if "--config" not in sys.argv:\n'
                 '            sys.argv.extend(["--config",str(pathlib.Path(d)/"config.json")])\n' if config else '')
              + f'        runpy.run_path(str(pathlib.Path(d)/{entry!r}),run_name="__main__")\n')
    output = Path(output); output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text(source,encoding='utf-8')
    print(output)


if __name__=='__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--entry',required=True); p.add_argument('--out',required=True); p.add_argument('--config')
    a = p.parse_args(); bundle(a.entry,a.out,a.config)
